CREATE TABLE AUTOMATION_LOGGING
  (
    CREATE_DATE DATE DEFAULT SYSDATE,
    API      VARCHAR2(255 CHAR) NOT NULL ENABLE,
    API_TYPE VARCHAR2(255 CHAR),
    REQUEST CLOB,
    RESPONSE CLOB,
    STACK_TRACE CLOB,
    EXECUTION_TIME NUMBER,
    EXECUTED_BY    VARCHAR2(100 CHAR),
    REMOTE_ADDRESS VARCHAR2(255 CHAR),
    CONSTRAINT AUTOMATION_PK PRIMARY KEY (CREATE_DATE, API)
  ) ;

  CREATE TABLE AUTOMATION_REPORT
    (
      CREATE_DATE DATE DEFAULT SYSDATE,
      ACTION VARCHAR2(255 CHAR),
      RULE VARCHAR2(255 CHAR),
      ERROR_CODE VARCHAR2(255 CHAR),
      ORDER_ID VARCHAR2(255 CHAR),
      STATUS VARCHAR2(255 CHAR)

    ) ;