version: '2'

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    container_name: 'zookeeper-server'
    networks:
      - ms-network
  kafka-server:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server  
    container_name: 'kafka-server'
    networks:
      - ms-network
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  ms-network:
    driver: bridge