spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.corp.amdocs.com/ossome/odo/oss-ms-architecture/cloud-config-server.git
          skipSslValidation: true
          username: jjaviya
          password: Jay@1992
#          uri: https://github.com/javiyacollection/cloud-config-server
#          skipSslValidation: true
#          proxy:
#            https:
#              host: genproxy
#              port: '8080'
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 9192
